# Generated by Django 5.0 on 2023-12-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0001_initial'),
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks_model',
            name='category',
        ),
        migrations.AddField(
            model_name='tasks_model',
            name='category',
            field=models.ManyToManyField(to='categories_app.categories_model'),
        ),
    ]
