# Generated by Django 5.0 on 2023-12-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_remove_tasks_model_category_tasks_model_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks_model',
            name='assign_date',
        ),
        migrations.AddField(
            model_name='tasks_model',
            name='assigned_date',
            field=models.DateTimeField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='tasks_model',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
