# Generated by Django 5.0 on 2023-12-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories_model',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
